# MySQL address, user and password
# user must have replication privilege in MySQL.
my_addr = "testdb.core-data.crowdpac.com:3306"
my_user = "cproot"
my_pass = "mpu9v92U7n4U7PqQ"

# Elasticsearch address
es_addr = "127.0.0.1:9200"

# Path to store data, like master.info, and dump MySQL data 
data_dir = "./var"

# Inner Http status address
stat_addr = "127.0.0.1:12800"

# pseudo server id like a slave 
server_id = 1001

# mysql or mariadb
flavor = "mysql"

# mysqldump execution path
mysqldump = "mydumper"

max_bulk_items = 5

# MySQL data source
[[source]]
schema = "cfdb"

tables = ["cand_db_small"]

[[rule]]
schema = "cfdb"
table = "cand_db_small"
index = "cand_db"
indexFile = "cand_db.idx.json"
type = "cand_db"
